import type { Metadata } from "next";

import "./globals.css";
import dynamic from "next/dynamic";
import Script from "next/script";
import Head from "next/head";



export const metadata: Metadata = {
  title: "Telegram Template Nextjs",
  description: "Generated by create next app",
};
const TelegramProvider = dynamic(() => import("@/app/ui/TelegramContext"), { ssr: false })
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <Script
          src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive"
        />
        <TelegramProvider>
          {children}
        </TelegramProvider>

      </body>
    </html>
  );
}
